Cloud bastion
Otus-DevOps-2020-08/KIT-IT_infra pull request #2
Opened 2020-09-28 13:52 UTC by KIT-IT

2020-09-29 08:32 UTC, mrgreyves requested changes
Здравствуйте!) Проверил ваше дз. Не хватает ключа для подключения к ovpn. ДЗ возвращаю на доработку.

2020-10-14 09:41 UTC, KIT-IT commented
Готово! Тесты пройдены.

2020-10-14 09:41 UTC, KIT-IT commented
> Здравствуйте!) Проверил ваше дз. Не хватает ключа для подключения к ovpn. ДЗ возвращаю на доработку.

Поправил. Тесты пройдены

2020-10-14 13:16 UTC, mrgreyves approved these changes
Здравствуйте!) Не забывайте добавлять описание к вашим пр. ДЗ принимаю!=)

2020-10-14 17:49 UTC, KIT-IT commented
Good

2020-10-14 17:50 UTC, merged